### ISSUE TITLE
Set CPU / Memory resources

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-forge/pangeo-forge-azure-bakery#11]
AFAICT, right now we don't have any CPU or memory resources, so pods might be evicted if the node is under memory pressure.

IIUC, they should be set at https://github.com/pangeo-forge/pangeo-forge-azure-bakery/blob/8c7c40183d3a0eedbaab7dac483287b8abf54c46/flow_test/oisst_recipe.py#L71-L80.

**Comment by TomAugspurger** [comment]
Also need to set this in the `KubernetesRun`. See https://github.com/pangeo-forge/pangeo-forge-azure-bakery/commit/56f7229f20b704e3a970af3dd29229317e54ba1a

**Comment by TomAugspurger** [comment]
My `prefect-job` pod was killed with those limits for using too much memory. Bumped to `8Gi`. I don't have a sense for what the `prefect-job` pod is doing, and why it would be loaded much data at all.

**Comment by ciaranevans** [comment]
Wow I'm glad GitHub has been keeping me up-to-date with these issues 🙃

**Comment by ciaranevans** [comment]
@TomAugspurger in terms of your list:

1. What values do you deem OK?
2. Seems that the `prefect_agent_conf.yaml` has sections for `JOB_MEM*|JOB_CPU*` so should those values go there?
3. I think you're right, this will be a default for now in `DaskExecutor` - I believe they're set to `None` now to allow for whatever they need.

**Comment by ciaranevans** [comment]
Hmmm okay so it looks like there _is_ a way to specify `scheduler|worker` resources in `KubeCluster`, so we should be good on that side.

**Comment by ciaranevans** [comment]
I can also set the job resources in `KubernetesRun` so that's a bit nicer.

**Comment by TomAugspurger** [comment]
Yeah, I think we have some default resources for the dask workers, which fits nicely into whatever VMs we're using. Then the recipe can perhaps override those values if they need higher memory.

**Comment by TomAugspurger** [comment]
FYI @ciaranevans, I believe that these are all of the orchestration changes I've made to my branch:

* setting Job requests in KubernetesRun: https://github.com/pangeo-forge/pangeo-forge-azure-bakery/compare/memory-debug?expand=1#diff-b4a38f17564695fb839c037798280e157bc1bc5f19d4ded9ec5ec7189552eb17R60
* setting worker / scheduler requests in `make_pod_spec`: https://github.com/pangeo-forge/pangeo-forge-azure-bakery/compare/memory-debug?expand=1#diff-b4a38f17564695fb839c037798280e157bc1bc5f19d4ded9ec5ec7189552eb17R75-R76 (might require changes to the Dockerfile to include kubectl, I don't recall: https://github.com/pangeo-forge/pangeo-forge-azure-bakery/compare/memory-debug?expand=1#diff-628e7ac1b519951c36b09c110013957aff7fbb1f648620e3d9a904a69ef3f7e2R5-R8)
* Adding a job template to prevent Jobs from being evicted (https://github.com/pangeo-forge/pangeo-forge-azure-bakery/compare/memory-debug?expand=1#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R44, https://github.com/pangeo-forge/pangeo-forge-azure-bakery/compare/memory-debug?expand=1#diff-2728a3912f8944b41b4b21756edd4d5d67b26a7034ea8913ed962b75b81db53dR23, and https://github.com/pangeo-forge/pangeo-forge-azure-bakery/compare/memory-debug?expand=1#diff-f820c849a692c24b508472c87e01696be9d4ba9816fe2b62fb8532d88e0568b8R1)


Could you extract those and apply them to the `main` branch?

**Comment by ciaranevans** [comment]
@TomAugspurger thanks, can you link to the lines in the branch view? For some reason 90% of those links take me to creating a PR so actually finding them is a pain 😅 

I think I've got most of them. Currently waiting on Prefect to get back to me with an issue we're gonna hit if we want to specify scheduler/worker memory.

**Comment by TomAugspurger** [comment]
> Currently waiting on Prefect to get back to me with an issue we're gonna hit if we want to specify scheduler/worker memory

What issue is that? AFAICT, it's working fine on my branch.

**Comment by ciaranevans** [comment]
Yours is applied to both with `pod_template` - I'm assuming you'd want the ability to define different values for the scheduler vs the workers?

**Comment by TomAugspurger** [comment]
That might be nice, but not a blocker IMO. We can just all of them to the largest we need for now.

And you might be aware, but KubeCluster supports a `scheduler_pod_template`: https://kubernetes.dask.org/en/latest/kubecluster.html#dask_kubernetes.KubeCluster. Perhaps that works (or doesn't work, because of some issue in prefect?)

**Comment by ciaranevans** [comment]
@TomAugspurger `scheduler_pod_template` is what's causing me grief. If we just use the `pod_template`, everything's just copied over, but I think that `scheduler_pod_template` causes some defaults to be missed somewhere, hence my issue so far.

We can definitely just stick to the same config for both for now, but the issue is under the spotlight anyway 🎉

**Comment by ciaranevans** [comment]
(I am actively working on putting these changes in, they're going in with the move to use DockerHub for images)

**Comment by ciaranevans** [comment]
@TomAugspurger Can you confirm your values to set are as follows:
* Job
  * mem: `3Gi`
  * cpu: `1`
* Scheduler/Workers
  * mem: `4Gi`
  * cpu: `1`

If this is the case, for the test flow I'll just set these manually. 

When it comes to `pangeo-forge-prefect`, we'll set these on the numbers provided by the meta.yaml (I think that's right @sharkinsspatial ?)

**Comment by ciaranevans** [comment]
@TomAugspurger I also have:
```yaml
requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
```
In my `prefect_agent_conf.yaml` for the agent resources - thoughts?

**Comment by TomAugspurger** [comment]
```
Scheduler/Workers
mem: 4Gi
cpu: 1
```

You might want to lower the requests a tad, so that we can pack two workers into a single VM. Kubernetes takes a bit of space from each pod. `kubectl describe nodes -o yaml` will have info how how much is allocatable.

I don't have a good sense for what the agent uses, but that seems fine.
