### ISSUE TITLE
Ciarans Handoff Notes

### ISSUE THREAD

**Issue by ciaranevans** [pangeo-forge/pangeo-forge-azure-bakery#14]
There's 2 main 'issues' currently with Prefect that will affect the `pangeo-forge-azure-bakery`:

- [x]  Log access
- [x]  Having different resources for the Dask Scheduler and the Workers

# Log Access

As mentioned in the README here: https://github.com/pangeo-forge/pangeo-forge-azure-bakery#logging, Dask Pods that are spun up are not labelled with anything linking them to the current Flow run. We've linked them to the Flow that's registered, see: https://github.com/pangeo-forge/pangeo-forge-azure-bakery/blob/main/flow_test/oisst_recipe.py#L91 but this doesn't alleviate the problem where you run 30 invocations of the same Flow and want to find the logs of a specific run.

I've raised the following issue https://github.com/PrefectHQ/prefect/issues/4617 on Prefect to see if we can somehow get `flow_run_id` to be a label on the Kubernetes Pods and potentially the ECS Tasks in the Azure Bakery.

For now, the best approach would be for our own logging statements to be prepended with `flow_run_id` so that we can search for logs that contain the value, rather than having to query the logs based on time and then back-engineer the container IDs to get logs from the workers, as explained in the README.

# Having different resources for the Dask Scheduler and the Workers

Currently, we've setup the Bakery to have the same resources for the Dask Scheduler and the Workers. You can see this where we define `pod_template` here: https://github.com/pangeo-forge/pangeo-forge-azure-bakery/blob/main/flow_test/oisst_recipe.py#L89-L101. 

Ideally, we would like to make use of the `scheduler_pod_template` kwarg in KubeCluster to allow us to specify different resource requirements for the Scheduler. Currently however, in Prefect, if we use both of the kwargs, we get an error. It appears that as soon as you use the `scheduler_pod_template`, that pod definition is missing some default values.

I've raised the following issue https://github.com/PrefectHQ/prefect/issues/4735 on Prefect to track this. It may very well be a `dask_kubernetes` specific issue, but it's during our Prefect Flow setup.

**Comment by tracetechnical** [comment]
Log access is addressed by #21

**Comment by tracetechnical** [comment]
Resources are handled by #30

**Comment by tracetechnical** [comment]
Closed by #21, #30
