### ISSUE TITLE
Query TF for bakery-database yaml entries.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/pangeo-forge-azure-bakery#16]
Bakery operators will be creating their own infrastructure and then registering this infrastructure with the `pangeo-forge` community by creating a PR on https://github.com/pangeo-forge/bakery-database/blob/main/bakeries.yaml  To facilitate correct entries we should create a small utility which queries TF for the relevant cluster entries and outputs a sample `yaml` file.  This should be included as a command in the `Makefile` as well.

**Comment by tracetechnical** [comment]
This should be fixed by #18
