### ISSUE TITLE
Define which k8s version we want to use

### ISSUE THREAD

**Issue by ciaranevans** [pangeo-forge/pangeo-forge-azure-bakery#2]
Currently whilst developing the bakery deployment, I've been using the latest version of Kubernetes that the `azurerm` provider sets. The guide I'm following [here](https://learn.hashicorp.com/tutorials/terraform/aks) however talks about enabling the Kubernetes dashboard and accessing it.

The most recent AKS documentation states that k8s versions `>=1.19` will no longer provide the Kubernetes dashboard addon, rather encouraging users to rely on https://docs.microsoft.com/en-us/azure/aks/kubernetes-portal

@TomAugspurger do you have a preference on this?

Having not actually used the 'original' dashboard, I've no real preference.

**Comment by TomAugspurger** [comment]
I haven't used it either. So going with the newest seems fine, to make updating later on easier.

**Comment by ciaranevans** [comment]
Cool, we'll go with the `azurerm` defaults then 🎉
