### ISSUE TITLE
Naming restrictions on variables

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-forge/pangeo-forge-azure-bakery#8]
My first couple attempts to deploy failed because Azure places some restrictions on the names of various objects. I believe all of these come from `TF_VAR_identifier` in the `.env` file.

My first attempt used dashes, and errored with

```

│ Error: name ("pangeo-forge-azure-testb") can only consist of lowercase letters and numbers, and must be between 3 and 24 characters long
│
│   with azurerm_storage_account.bakery_flow_storage_account,
│   on main.tf line 41, in resource "azurerm_storage_account" "bakery_flow_storage_account":
│   41: resource "azurerm_storage_account" "bakery_flow_storage_account" {
│

```

So we can't have dashes.

My second attempt used a long-ish name, and failed when creating the AKS cluster

```
│ Error: creating Managed Kubernetes Cluster "pangeoforgetest-bakery-cluster" (Resource Group "pangeoforgetest-bakery-resource-group"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The length of the node resource group name is too long. The maximum length is 80 and the length of the value provided is 82. Please see https://aka.ms/aks-naming-rules for more details." Target="name"
│
 ```

AKS creates [two resource groups](https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks), the second of which includes a pre- and postfix so it gets a bit long. 

We can maybe make a smaller postfix. I believe we add `-bakery-cluster`. Maybe that can be dropped?

After those two failures, things seemed to work well. Trying it out now!

**Comment by ciaranevans** [comment]
@TomAugspurger I'd be happy to just set the `name` on resources to `var.identifier` if that means we get a bit more flexibility.

I'm open on suggestions on this one, AWS has been somewhat forgiving on me so the Azure naming restrictions are new haha

**Comment by ciaranevans** [comment]
@TomAugspurger I gave it a go putting stuff to just `var.identifier`, it doesn't make it _as_ easy to immediately identify what's what (unless you're good with your Azure icons)

```
Outputs:

bakery_cluster_name = "ciarandev"
bakery_flow_storage_account_name = "ciarandevbakeryflowstora"
bakery_flow_storage_container_name = "ciarandev"
bakery_image_registry_name = "ciarandevbakeryimageregistry"
bakery_resource_group_name = "ciarandev"
```

Still need something unique in the registry and storage account name as they're globally unique...

I wonder if we'd rather just name stuff like 'bakery-storage-container`

Stuff that needs uniqueness can include the identifier (limited to length if needed of course).

**Comment by ciaranevans** [comment]
Or... we leave it and just make a note to try and keep identifiers short (and without `-`'s)
