### ISSUE TITLE
Flow submission / execution environment mismatch

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-forge/pangeo-forge-azure-bakery#9]
I was modifying some dependencies (installing a new version of adlfs) and somehow got into a bad state where my flow runs wouldn't execute. The error messages were something like

```
[9 June 2021 10:23am]: Failed to load and execute Flow's environment: StorageError("An error occurred while unpickling the flow:\n UnpicklingError('state is not a dictionary')\nThis may be due to one of the following version mismatches between the flow build and execution environments:\n - python: (flow built with '3.8.3', currently running with '3.8.10')")
```

What are the requirements between the environment registering the flow and the environment executing it?

As a workaround, I used the execution environment to submit the flow:

```
$ poetry run dotenv run docker run -it --rm \
    -v (pwd)/flow_test/oisst_recipe.py:/oisst_recipe.py \
    -e FLOW_STORAGE_CONNECTION_STRING -e FLOW_STORAGE_CONTAINER -e AZURE_BAKERY_IMAGE \
    -e PREFECT__CLOUD__AGENT__LABELS -e PREFECT_PROJECT -e PREFECT__CLOUD__AUTH_TOKEN \
    pftbakeryimageregistry.azurecr.io/pangeo-forge-azure-bakery-image:latest python3 /oisst_recipe.py

```

**Comment by ciaranevans** [comment]
So the versions registered with **must** equal the versions on the execution environment, your method of registration is actually much nicer to be honest. We can probably use that in the docs. 

Then you're guaranteed to be on the exact same versions when registering & executing (This is what the `pangeo-forge-prefect` package does)
